## 端口设置
server:
  port: 8087
spring:
  application:
    name: simulation-project-es
  datasource:
    username:
    password:
    url: jdbc:mysql://:3306/wisdombrain?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  ## redis配置
  redis:
    host:
    port: 6379
    timeout: 6000ms
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
    database: 4
  data:
    ## es配置
    elasticsearch:
      cluster-nodes:
      cluster-name: elasticsearch
## eureka客户端配置
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: simulation-project-es   #自定义服务名称信息
    prefer-ip-address: true     #访问路径可以显示IP地址
info:
  app.name: simulation-project-es
  company.name: cn.xuxiaonan
  build.artifactId: $project.artifactId$
  build.version: $project.version$
## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml